"""Renders a Markdown incident report from a RootCauseReport.

This is the artifact that lands as a DataHub incident annotation AND as a
GitHub PR comment when a contract check fails.  The whole value of the
agent sits in *this* output — a junior engineer reading it should know
exactly what to investigate next without having to read any other code.
"""

from __future__ import annotations

from datetime import datetime, timezone

from dhqa.dataset_model import DatasetContract
from dhqa.lineage_tracer import RootCauseReport
from dhqa.test_generator import CheckResult


def render_incident_report(
    report: RootCauseReport,
    contract: DatasetContract | None = None,
    all_results: list[CheckResult] | None = None,
) -> str:
    """Return a Markdown incident report.

    Includes:
      - The failing check (and which dataset / column it affected)
      - The full lineage walk, hop by hop, with status icons
      - A plain-English conclusion (origin dataset)
      - Action items for the on-call engineer
    """
    failing = report.failing_check
    short_origin = _short(report.origin_urn)
    short_failing = _short(failing.detail or report.failing_check.check_id)

    lines = [
        f"# Incident Report -- {failing.kind} check failed",
        "",
        f"**Generated**: `{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}`  ",
        f"**Root cause traced via**: DataHub lineage graph (re-executed at each hop)  ",
        f"**Origin dataset**: `{report.origin_urn}`  ",
        f"**Hop distance**: {report.hop_distance}  ",
        f"**Failing check**: `{failing.check_id}` ({failing.kind} on `{failing.column or 'dataset-level'}`)  ",
        "",
        "## Summary",
        "",
        f"Contract check **`{failing.check_id}`** failed: `{short_failing}`.",
        "",
        f"The lineage walker traced **{report.hop_distance} hop(s) upstream** and "
        f"identified `{short_origin}` as the dataset where the anomaly originates.",
        "",
        "## Lineage walk",
        "",
    ]

    if not report.trace:
        lines.append("_No upstream ancestors to walk -- the anomaly originates in the current dataset itself._")
        lines.append("")
    else:
        for hop in report.trace:
            icon = "[PASS]" if hop.get("passed") else "[FAIL]"
            short_urn = _short(hop["urn"])
            info = hop.get("detail", "")
            check = hop.get("checked", "")
            lines.append(
                f"- {icon} **`{short_urn}`** -- `{check}`: {info}"
            )
        lines.append("")

    if contract is not None:
        reasons: list[str] = []
        for c in contract.constraints:
            if c.kind != failing.kind:
                continue
            if failing.kind in ("unique", "not_null"):
                reasons.append(
                    f"- DOM contract for `{short_origin}` declares "
                    f"`{c.kind}` on `{c.column}` (from DataHub schema metadata)."
                )
            elif failing.kind == "freshness":
                reasons.append(
                    f"- DOM contract declares a freshness SLA of {c.max_staleness_hours}h "
                    f"on column `{c.column}`."
                )
            elif failing.kind == "referential":
                short_ref = _short(c.ref_urn or "the upstream parent")
                reasons.append(
                    f"- DOM contract for `{short_origin}` declares a `referential` "
                    f"constraint on `{c.column}` -> `{short_ref}` "
                    f"(every key must exist in the declared upstream parent)."
                )
        if reasons:
            lines.append("## Why we caught this")
            lines.append("")
            lines.extend(reasons)
            lines.append("")

    lines.extend([
        "## Action items",
        "",
        "1. Investigate the upstream transformation logic for the failing column.",
        "2. Confirm that the dbt test on the failing column is not silenced.",
        "3. If the anomaly is intentional, update the DataHub contract on the "
        "origin dataset.",
        "",
        "---",
        "_This report was auto-generated by `dhqa` from a "
        "DataHub lineage walk -- it doesn't stop at 'check failed', it "
        "follows the data graph until it finds where the issue started._",
    ])

    return "\n".join(lines) + "\n"


def _short(urn: str) -> str:
    """Shorten ``urn:li:dataset:(urn:li:dataPlatform:snowflake,name,PROD)``
    -> ``name`` and ``orders.fact_orders`` -> ``fact_orders``."""
    if not urn:
        return urn
    if "," in urn:
        parts = urn.split(",")
        for p in parts:
            if "." in p or "_" in p:
                tail = p.strip().strip(")")
                if "." in tail:
                    tail = tail.split(".")[-1]
                return tail
        return parts[1].strip().strip(")")
    return urn
